### ISSUE TITLE
Set interval as a member variable

### ISSUE THREAD

**Issue by Mietzsche81** [JoeMuff999/PID_Project#1]
https://github.com/JoeMuff999/PID_Project/blob/1e140a9eb1263ba9ca224675549882fd4ac75023/SIM_Satellite/models/ISS/analytical/satellite_dynamics.cpp#L11

We need to be able to set this value from the input file.

**Comment by Mietzsche81** [comment]
Make this a public member variable in Satellite so that we can overwrite whatever default value the constructor gives in the input file.

**Comment by JoeMuff999** [comment]
fixed
