### ISSUE TITLE
Extraneous Pointer argument

### ISSUE THREAD

**Issue by Mietzsche81** [JoeMuff999/PID_Project#2]
https://github.com/JoeMuff999/PID_Project/blob/1e140a9eb1263ba9ca224675549882fd4ac75023/SIM_Satellite/models/ISS/analytical/satellite_dynamics.cpp#L9

https://github.com/JoeMuff999/PID_Project/blob/1e140a9eb1263ba9ca224675549882fd4ac75023/SIM_Satellite/models/ISS/analytical/satellite_dynamics.cpp#L54

Satellite S is passed as an input, but never used (i.e.: we just use `r[i]` instead of `S->r[i]`)

If you implemented a dynamics manager class, we would want to pass in a satellite e.g.:
`Dynamics::update_satellite(Satellite* S)`

But here, the satellite is updating itself, so it doesn't need to pass in itself as an argument, so change to:
`Satellite::satellite_Dynamics()`
`Satellite::satellite_printState()`

**Comment by JoeMuff999** [comment]
fixed
