### ISSUE TITLE
Do not set initial state during initialize, set these via input file.

### ISSUE THREAD

**Issue by Mietzsche81** [JoeMuff999/PID_Project#3]
https://github.com/JoeMuff999/PID_Project/blob/1e140a9eb1263ba9ca224675549882fd4ac75023/SIM_Satellite/models/ISS/analytical/satellite_init.cpp#L18-L58

We don't want to have to recompile the program every time we want to tweak our initial state: the source code should follow the same process, we just need to start from a different point. That's why Trick has the handy input file architecture.

**Comment by JoeMuff999** [comment]
fixed
