### ISSUE TITLE
Is this ever called?

### ISSUE THREAD

**Issue by Mietzsche81** [JoeMuff999/PID_Project#5]
https://github.com/JoeMuff999/PID_Project/blob/1e140a9eb1263ba9ca224675549882fd4ac75023/SIM_Satellite/models/Controllers/src/pid.cpp#L35-L39

Currently extraneous. get's & set's functions are usually used for manipulating private variables that can't be set directly in other functions. i.e.: the satellite wants to update PID's error, but the error is private (because only the PID should be allowed to set its own error), so the satellite calls a PID::setError() function to set it, or a PID::getError() function to just have PID return the error value, which is hidden from satellite by virtue of privacy.

**Comment by JoeMuff999** [comment]
Fixed
